language: android
jdk: oraclejdk8
branches:
  only:
    - master
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'

notifications:
  email: false

before_install:

  # for gradle output style
  - chmod +x gradlew
  - export TERM=dumb
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --no-ui --filter build-tools-23.0.2,android-23

# Let's try to build...
script: TERM=dumb ./gradlew build
