language: android
jdk: oraclejdk8
sudo: require
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'
    - '.*'

notifications:
  email: false

env:
  global:
    - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}
 
  
before_install:

  # for gradle output style
#  - chmod +x gradlew
#  - export TERM=dumb
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - sudo ls -ltr /usr/local/android-sdk
  - android update sdk --no-ui --filter build-tools-23.0.2,android-23

# Let's try to build...
script: TERM=dumb ./gradlew build
