language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - ANDROID_API=26
    - EMULATOR_API=26
    - ANDROID_BUILD_TOOLS=26.0.2
    #- ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    #- PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}
 
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'
    - '.*'

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
# for gradle output style
#  - chmod +x gradlew
#  - export TERM=dumb
#  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
#  - android update sdk --no-ui --filter build-tools-23.0.2,android-23
#  - sudo cp -R /usr/local/android-sdk-25.2.3 ${ANDROID_HOME}
#  - sudo ls -ltr ${ANDROID_HOME}
#  - sudo touch ${ANDROID_HOME}/licenses/android-sdk-license
#  - sudo chown travis:travis -R ${ANDROID_HOME}
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - $ANDROID_HOME/tools/bin/sdkmanager --licenses
  - chmod +x gradlew
  - ./gradlew dependencies || true

# Let's try to build...
script: 
  - "./gradlew clean build"
