language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'
    - '.*'

notifications:
  email: false

env:
  global:
    - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}
 
  
before_install:

  # for gradle output style
#  - chmod +x gradlew
#  - export TERM=dumb
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --no-ui --filter build-tools-23.0.2,android-23
  - sudo ls -ltr /usr/local/android-sdk
  - whoami
  - sudo cp -R /usr/local/android-sdk-25.2.3 ${ANDROID_HOME}
  - sudo ls -ltr ${ANDROID_HOME}
  - sudo mkdir ${ANDROID_HOME}/licenses
  - sudo touch ${ANDROID_HOME}/licenses/android-sdk-license
  - sudo chown travis:travis -R ${ANDROID_HOME}
  - sudo echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55" > ${ANDROID_HOME}/licenses/android-sdk-license

# Let's try to build...
script: TERM=dumb ./gradlew clean build
