language: android
jdk: oraclejdk8
branches:
  only:
    - master
android:
  components:
    - build-tools-23.0.3
    - android-23

notifications:
  email: false

before_install:

  # for gradle output style
  - chmod +x gradlew
  - export TERM=dumb
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

# Let's try to build...
script: TERM=dumb ./gradlew clean build