language: android
android:
  components:
    - build-tools-23.0.3

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

# Let's try to build...
script: ./gradlew clean build