language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-23.0.3
    - android-23

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

# Let's try to build...
script: ./gradlew clean build