language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - tools-23.0.3
    - build-tools-23.0.3
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'

notifications:
  email: false

before_install:

  # for gradle output style
  - chmod +x gradlew
  - export TERM=dumb
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --no-ui --filter build-tools-23.0.2,android-23
  - sudo ls -ltr /usr/local/android-sdk/licenses
  - sudo echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55" > "/usr/local/android-sdk/licenses/android-sdk-license"

# Let's try to build...
script: TERM=dumb ./gradlew build
