language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-23.0.3
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

# Let's try to build...
script: ./gradlew clean build