language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - ANDROID_API=30
    - EMULATOR_API=30
    - ANDROID_BUILD_TOOLS=30.0.2
    - LC_ALL='de_DE.UTF-8'

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'
    - '.*'

addons:
  apt:
    packages:
      - language-pack-de

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - 'if [ -n "$TRAVIS_TAG" ]; then openssl aes-256-cbc -K $encrypted_6ab911f61ce6_key -iv $encrypted_6ab911f61ce6_iv -in keystore.ks.enc -out keystore.ks -d; else echo "Not building a tagged commit! Skipping decrypting!"; fi'

script:
  - ./gradlew jacocoTestReport coveralls
  - 'if [ -n "$TRAVIS_TAG" ]; then ./gradlew clean assembleRelease; else echo "Not building a tagged commit! Skipping building release apk!"; fi'

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: SI7N7wUJfpmI3H0qL7UUDP3YKnbGMRz0PSbTcVqSDxk/4JE6Mwy5PPOJIn0kH2mQ+Yj2wKNF7f6jkTjQd8ZnkV4tv8UkjG3uRbLaGKyA1KOvJ9ZKIVFMen65dKLQI/kg6iU7+3YGpFLuqEaeHOEVz+zC1yfzSi927B3AZsF6QuJN9eNSKKIARKPCZi+/XMi4+tqGKyUtPntu6Cd4Nb12qZd5l9NwMdKcxrP0ux13j5Q+aYxFz1Oibye7TIdb3ucQ1KiQ21653fHhxB902ytZClbbyP8xfLOLZ/BrEadOUYuRVQM2whJXD32GLZ9Ue2ofuUayxkKabXrIUOsOlgXqQcE0G89c8kHB72B9K+SMad7pBW1uOOqW0QRqOv5XEziQ71nVM5SqFpbuV5ORJQZvlvScxRq4JxNIyw+fkyrYSbNoPIQLrAv/GW5PDFKlzsbL4KW55CGZPdOGhDcjcHePni/LSDm5MLj3zfTWLbxmzEVSlmHzCOaAuGgryst2HuIFX8oLkdBjTT3Hr/62a6zC0CQmsqu/qTjLhg9ZLNEPx8yB3XhgkeyaKj+Ue2nlq9iZb3zR3fwBs5V67/+p7h0l6Ssph5xNSsqH68Cj6W77Onuz2aDkNONfGtA6NrPMeSBOe+pP7LxQOPDBeUTibDX9BS43mVEOmGwG00h+jMc4pXQ=
  file_glob: true
  file:
    - "/home/travis/build/d-Rickyy-b/MGGVertretungsplan/app/build/outputs/apk/release/*.apk"
    - "/home/travis/build/d-Rickyy-b/MGGVertretungsplan/app/build/outputs/mapping/release/mapping.txt"
  on:
    repo: d-Rickyy-b/MGGVertretungsplan
    # branch: master
    tags: true
