# GitHub Actions Workflow for running tests for the Android app
name: test

on:
  push:
    branches: [ master, dev, date-fix ]
  pull_request:
    branches: [ master ]

env:
  LANG: "de_DE.UTF-8"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Locale - de_DE.UTF-8
        run: |
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8

      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew jacocoTestReport coveralls
